[2023-12-07T07:49:40.887+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.loading_v_table manual__2023-12-07T07:49:39.592733+00:00 [queued]>
[2023-12-07T07:49:40.892+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.loading_v_table manual__2023-12-07T07:49:39.592733+00:00 [queued]>
[2023-12-07T07:49:40.893+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-12-07T07:49:40.903+0000] {taskinstance.py:1380} INFO - Executing <Task(SnowflakeOperator): loading_v_table> on 2023-12-07 07:49:39.592733+00:00
[2023-12-07T07:49:40.908+0000] {standard_task_runner.py:57} INFO - Started process 310 to run task
[2023-12-07T07:49:40.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'loading_v_table', 'manual__2023-12-07T07:49:39.592733+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp1fgqpsv9']
[2023-12-07T07:49:40.911+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask loading_v_table
[2023-12-07T07:49:40.943+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.loading_v_table manual__2023-12-07T07:49:39.592733+00:00 [running]> on host 5e36d60cd939
[2023-12-07T07:49:40.995+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='loading_v_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-07T07:49:39.592733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-07T07:49:39.592733+00:00'
[2023-12-07T07:49:40.997+0000] {sql.py:274} INFO - Executing: <property object at 0x7fa47de6d810>
[2023-12-07T07:49:41.005+0000] {base.py:73} INFO - Using connection ID 'snowflake' for task execution.
[2023-12-07T07:49:41.011+0000] {base.py:73} INFO - Using connection ID 'snowflake' for task execution.
[2023-12-07T07:49:41.012+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-12-07T07:49:41.012+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-12-07T07:49:41.013+0000] {connection.py:1060} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-12-07T07:49:41.013+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-12-07T07:49:41.256+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2023-12-07T07:49:41.589+0000] {cursor.py:804} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-12-07T07:49:41.698+0000] {cursor.py:817} INFO - query execution done
[2023-12-07T07:49:41.698+0000] {cursor.py:959} INFO - Number of results in first chunk: 1
[2023-12-07T07:49:41.699+0000] {connection.py:640} INFO - closed
[2023-12-07T07:49:41.786+0000] {connection.py:646} INFO - No async queries seem to be running, deleting session
[2023-12-07T07:49:41.873+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 414, in run
    for sql_statement in sql_list:
TypeError: 'property' object is not iterable
[2023-12-07T07:49:41.879+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=Georgy, task_id=loading_v_table, execution_date=20231207T074939, start_date=20231207T074940, end_date=20231207T074941
[2023-12-07T07:49:41.889+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 205 for task loading_v_table ('property' object is not iterable; 310)
[2023-12-07T07:49:41.925+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-07T07:49:41.941+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
