[2023-12-04T09:07:53.909+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:07:53.915+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:07:53.915+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:07:53.924+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T09:07:53.928+0000] {standard_task_runner.py:57} INFO - Started process 656 to run task
[2023-12-04T09:07:53.931+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppkx_n54g']
[2023-12-04T09:07:53.931+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask updates
[2023-12-04T09:07:53.963+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T09:07:54.014+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T09:07:54.015+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:07:54.016+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo apt update -S']
[2023-12-04T09:07:54.023+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:07:54.027+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:07:54.028+0000] {subprocess.py:93} INFO - We trust you have received the usual lecture from the local System
[2023-12-04T09:07:54.028+0000] {subprocess.py:93} INFO - Administrator. It usually boils down to these three things:
[2023-12-04T09:07:54.028+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:07:54.029+0000] {subprocess.py:93} INFO -     #1) Respect the privacy of others.
[2023-12-04T09:07:54.029+0000] {subprocess.py:93} INFO -     #2) Think before you type.
[2023-12-04T09:07:54.029+0000] {subprocess.py:93} INFO -     #3) With great power comes great responsibility.
[2023-12-04T09:07:54.029+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:07:54.029+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2023-12-04T09:07:54.030+0000] {subprocess.py:93} INFO - sudo: a password is required
[2023-12-04T09:07:54.030+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T09:07:54.038+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T09:07:54.040+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T090753, end_date=20231204T090754
[2023-12-04T09:07:54.049+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task updates (Bash command failed. The command returned a non-zero exit code 1.; 656)
[2023-12-04T09:07:54.062+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T09:07:54.082+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T09:12:30.791+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:12:30.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:12:30.796+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:12:30.806+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T09:12:30.810+0000] {standard_task_runner.py:57} INFO - Started process 733 to run task
[2023-12-04T09:12:30.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmprfpjj0kw']
[2023-12-04T09:12:30.813+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask updates
[2023-12-04T09:12:30.845+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T09:12:30.895+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T09:12:30.896+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:12:30.897+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo apt install -y python3 python3-dev python3-venv']
[2023-12-04T09:12:30.905+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:12:30.909+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:12:30.910+0000] {subprocess.py:93} INFO - We trust you have received the usual lecture from the local System
[2023-12-04T09:12:30.910+0000] {subprocess.py:93} INFO - Administrator. It usually boils down to these three things:
[2023-12-04T09:12:30.910+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO -     #1) Respect the privacy of others.
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO -     #2) Think before you type.
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO -     #3) With great power comes great responsibility.
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2023-12-04T09:12:30.911+0000] {subprocess.py:93} INFO - sudo: a password is required
[2023-12-04T09:12:30.912+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T09:12:30.919+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T09:12:30.922+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T091230, end_date=20231204T091230
[2023-12-04T09:12:30.931+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task updates (Bash command failed. The command returned a non-zero exit code 1.; 733)
[2023-12-04T09:12:30.945+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T09:12:30.963+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T09:16:32.401+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:16:32.407+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T09:16:32.408+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:16:32.417+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T09:16:32.421+0000] {standard_task_runner.py:57} INFO - Started process 802 to run task
[2023-12-04T09:16:32.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6tly19vm']
[2023-12-04T09:16:32.424+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask updates
[2023-12-04T09:16:32.459+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T09:16:32.511+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T09:16:32.512+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:16:32.513+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T09:16:32.522+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:16:33.581+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T09:16:34.367+0000] {subprocess.py:93} INFO - Collecting kaggle
[2023-12-04T09:16:34.733+0000] {subprocess.py:93} INFO -   Downloading kaggle-1.5.16.tar.gz (83 kB)
[2023-12-04T09:16:34.890+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 kB 520.5 kB/s eta 0:00:00
[2023-12-04T09:16:34.907+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): started
[2023-12-04T09:16:35.608+0000] {subprocess.py:93} INFO -   Preparing metadata (setup.py): finished with status 'done'
[2023-12-04T09:16:35.614+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T09:16:35.615+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T09:16:35.615+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T09:16:35.615+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T09:16:35.904+0000] {subprocess.py:93} INFO - Collecting tqdm
[2023-12-04T09:16:35.986+0000] {subprocess.py:93} INFO -   Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
[2023-12-04T09:16:36.076+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 890.9 kB/s eta 0:00:00
[2023-12-04T09:16:36.080+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T09:16:36.080+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T09:16:36.237+0000] {subprocess.py:93} INFO - Collecting bleach
[2023-12-04T09:16:36.350+0000] {subprocess.py:93} INFO -   Downloading bleach-6.1.0-py3-none-any.whl (162 kB)
[2023-12-04T09:16:36.925+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.8/162.8 kB 370.1 kB/s eta 0:00:00
[2023-12-04T09:16:37.035+0000] {subprocess.py:93} INFO - Collecting webencodings
[2023-12-04T09:16:37.166+0000] {subprocess.py:93} INFO -   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
[2023-12-04T09:16:37.245+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T09:16:37.250+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T09:16:37.250+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T09:16:37.274+0000] {subprocess.py:93} INFO - Building wheels for collected packages: kaggle
[2023-12-04T09:16:37.275+0000] {subprocess.py:93} INFO -   Building wheel for kaggle (setup.py): started
[2023-12-04T09:16:38.205+0000] {subprocess.py:93} INFO -   Building wheel for kaggle (setup.py): finished with status 'done'
[2023-12-04T09:16:38.206+0000] {subprocess.py:93} INFO -   Created wheel for kaggle: filename=kaggle-1.5.16-py3-none-any.whl size=110683 sha256=f64ffbab074870423397c119e7365fcc7489bd971282e5624d97b544fa126dc5
[2023-12-04T09:16:38.206+0000] {subprocess.py:93} INFO -   Stored in directory: /home/***/.cache/pip/wheels/5a/ab/50/e224f599a07faf6d398a8600796012da271b7e5e7f2a3ab2b8
[2023-12-04T09:16:38.208+0000] {subprocess.py:93} INFO - Successfully built kaggle
[2023-12-04T09:16:42.145+0000] {subprocess.py:93} INFO - Installing collected packages: webencodings, tqdm, bleach, kaggle
[2023-12-04T09:16:42.438+0000] {subprocess.py:93} INFO - Successfully installed bleach-6.1.0 kaggle-1.5.16 tqdm-4.66.1 webencodings-0.5.1
[2023-12-04T09:16:42.864+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:16:42.865+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T09:16:42.866+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T09:16:43.053+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T09:16:43.071+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T091632, end_date=20231204T091643
[2023-12-04T09:16:43.119+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T09:16:43.133+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:23:13.777+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:23:13.783+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:23:13.783+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:23:13.793+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:23:13.797+0000] {standard_task_runner.py:57} INFO - Started process 1889 to run task
[2023-12-04T10:23:13.799+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplss70pai']
[2023-12-04T10:23:13.800+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask updates
[2023-12-04T10:23:13.834+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:23:13.884+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:23:13.886+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:23:13.886+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:23:13.895+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:23:14.825+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:23:14.999+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:23:15.003+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:23:15.004+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:23:15.004+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:23:15.004+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:23:15.004+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:23:15.005+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:23:15.005+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:23:15.005+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:23:15.010+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:23:15.014+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:23:15.019+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:23:15.019+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:23:18.876+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:23:18.877+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:23:18.877+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:23:19.034+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:23:19.052+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T102313, end_date=20231204T102319
[2023-12-04T10:23:19.093+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:23:19.112+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:32:35.682+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:32:35.688+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:32:35.688+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:32:35.698+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:32:35.702+0000] {standard_task_runner.py:57} INFO - Started process 2129 to run task
[2023-12-04T10:32:35.704+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpsdkqek6g']
[2023-12-04T10:32:35.705+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask updates
[2023-12-04T10:32:35.739+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:32:35.796+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:32:35.798+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:32:35.799+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:32:35.809+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:32:36.748+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:32:36.923+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:32:36.928+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:32:36.928+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:32:36.928+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:32:36.929+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:32:36.929+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:32:36.929+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:32:36.930+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:32:36.930+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:32:36.934+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:32:36.938+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:32:36.944+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:32:36.944+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:32:40.612+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:32:40.612+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:32:40.613+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:32:40.751+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:32:40.769+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T103235, end_date=20231204T103240
[2023-12-04T10:32:40.799+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:32:40.819+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:34:58.934+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:34:58.940+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:34:58.940+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:34:58.950+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:34:58.954+0000] {standard_task_runner.py:57} INFO - Started process 2192 to run task
[2023-12-04T10:34:58.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpwkmjji29']
[2023-12-04T10:34:58.957+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask updates
[2023-12-04T10:34:58.991+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:34:59.039+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:34:59.040+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:34:59.041+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:34:59.050+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:34:59.985+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:35:00.173+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:35:00.178+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:35:00.178+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:35:00.179+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:35:00.179+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:35:00.180+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:35:00.180+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:35:00.180+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:35:00.181+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:35:00.184+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:35:00.189+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:35:00.194+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:35:00.194+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:35:03.977+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:35:03.978+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:35:03.978+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:35:04.137+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:35:04.155+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T103458, end_date=20231204T103504
[2023-12-04T10:35:04.170+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:35:04.190+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:39:14.001+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:39:14.008+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:39:14.008+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:39:14.017+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:39:14.022+0000] {standard_task_runner.py:57} INFO - Started process 2280 to run task
[2023-12-04T10:39:14.024+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpd5rx5naa']
[2023-12-04T10:39:14.025+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask updates
[2023-12-04T10:39:14.059+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:39:14.109+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:39:14.110+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:39:14.111+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:39:14.119+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:39:15.093+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:39:15.260+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:39:15.264+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:39:15.264+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:39:15.265+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:39:15.265+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:39:15.265+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:39:15.265+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:39:15.266+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:39:15.266+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:39:15.269+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:39:15.274+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:39:15.280+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:39:15.281+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:39:19.002+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:39:19.003+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:39:19.003+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:39:19.155+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:39:19.173+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T103914, end_date=20231204T103919
[2023-12-04T10:39:19.200+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:39:19.219+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:41:14.910+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:41:14.916+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:41:14.916+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:41:14.926+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:41:14.930+0000] {standard_task_runner.py:57} INFO - Started process 2335 to run task
[2023-12-04T10:41:14.932+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp4hzblibd']
[2023-12-04T10:41:14.933+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask updates
[2023-12-04T10:41:14.967+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:41:15.016+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:41:15.017+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:41:15.018+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:41:15.027+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:41:15.969+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:41:16.164+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:41:16.170+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:41:16.171+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:41:16.171+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:41:16.171+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:41:16.171+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:41:16.172+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:41:16.172+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:41:16.172+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:41:16.176+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:41:16.181+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:41:16.186+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:41:16.187+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:41:19.980+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:41:19.980+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:41:19.980+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:41:20.139+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:41:20.157+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T104114, end_date=20231204T104120
[2023-12-04T10:41:20.186+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:41:20.206+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:50:24.275+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:50:24.281+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:50:24.281+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:50:24.291+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:50:24.297+0000] {standard_task_runner.py:57} INFO - Started process 2496 to run task
[2023-12-04T10:50:24.301+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplnlbhz9u']
[2023-12-04T10:50:24.302+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask updates
[2023-12-04T10:50:24.343+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:50:24.397+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:50:24.399+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:50:24.400+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:50:24.410+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:50:25.359+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:50:25.528+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:50:25.532+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:50:25.533+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:50:25.533+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:50:25.534+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:50:25.534+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:50:25.535+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:50:25.535+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:50:25.535+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:50:25.539+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:50:25.544+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:50:25.549+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:50:25.550+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:50:29.393+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:50:29.393+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:50:29.394+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:50:29.545+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:50:29.563+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T105024, end_date=20231204T105029
[2023-12-04T10:50:29.595+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:50:29.614+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:53:13.439+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:53:13.447+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:53:13.447+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:53:13.456+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:53:13.461+0000] {standard_task_runner.py:57} INFO - Started process 2569 to run task
[2023-12-04T10:53:13.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7j_woyxr']
[2023-12-04T10:53:13.464+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask updates
[2023-12-04T10:53:13.499+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:53:13.551+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:53:13.553+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:53:13.554+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:53:13.563+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:53:14.480+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:53:14.651+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:53:14.655+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:53:14.656+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:53:14.656+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:53:14.657+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:53:14.657+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:53:14.657+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:53:14.657+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:53:14.659+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:53:14.663+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:53:14.668+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:53:14.673+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:53:14.673+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:53:18.320+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:53:18.321+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:53:18.321+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:53:18.454+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:53:18.472+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T105313, end_date=20231204T105318
[2023-12-04T10:53:18.489+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:53:18.512+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T11:02:26.644+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:02:26.650+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:02:26.651+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T11:02:26.660+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T11:02:26.664+0000] {standard_task_runner.py:57} INFO - Started process 2728 to run task
[2023-12-04T11:02:26.667+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_jgy63f6']
[2023-12-04T11:02:26.668+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask updates
[2023-12-04T11:02:26.705+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T11:02:26.765+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T11:02:26.767+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T11:02:26.768+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T11:02:26.777+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T11:02:27.710+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T11:02:27.891+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T11:02:27.895+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T11:02:27.896+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T11:02:27.896+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T11:02:27.896+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T11:02:27.897+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T11:02:27.897+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T11:02:27.897+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T11:02:27.898+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T11:02:27.901+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T11:02:27.905+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T11:02:27.911+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T11:02:27.912+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T11:02:31.600+0000] {subprocess.py:93} INFO - 
[2023-12-04T11:02:31.601+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T11:02:31.601+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T11:02:31.759+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T11:02:31.779+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T110226, end_date=20231204T110231
[2023-12-04T11:02:31.801+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T11:02:31.820+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-12-04T11:05:16.891+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:05:16.896+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:05:16.897+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T11:05:16.906+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-11-30 21:10:00+00:00
[2023-12-04T11:05:16.910+0000] {standard_task_runner.py:57} INFO - Started process 2800 to run task
[2023-12-04T11:05:16.912+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpfjgsw6wd']
[2023-12-04T11:05:16.913+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask updates
[2023-12-04T11:05:16.946+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T11:05:16.995+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T11:05:16.996+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T11:05:16.997+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T11:05:17.005+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T11:05:17.951+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T11:05:18.122+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T11:05:18.126+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T11:05:18.126+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T11:05:18.127+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T11:05:18.127+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T11:05:18.127+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T11:05:18.128+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T11:05:18.128+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T11:05:18.128+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T11:05:18.132+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T11:05:18.137+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T11:05:18.142+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T11:05:18.143+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T11:05:21.932+0000] {subprocess.py:93} INFO - 
[2023-12-04T11:05:21.932+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T11:05:21.933+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T11:05:22.136+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T11:05:22.154+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231130T211000, start_date=20231204T110516, end_date=20231204T110522
[2023-12-04T11:05:22.207+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T11:05:22.227+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
