[2023-12-04T10:32:45.795+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:32:45.801+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:32:45.801+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:32:45.811+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:32:45.815+0000] {standard_task_runner.py:57} INFO - Started process 2155 to run task
[2023-12-04T10:32:45.818+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8lzniqe3']
[2023-12-04T10:32:45.819+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask copying_file
[2023-12-04T10:32:45.853+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:32:45.902+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:32:45.903+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:32:45.904+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T10:32:45.913+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:32:45.915+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T10:32:45.915+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:32:45.923+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:32:45.926+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T103245, end_date=20231204T103245
[2023-12-04T10:32:45.935+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2155)
[2023-12-04T10:32:45.950+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:32:45.969+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:35:09.117+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:35:09.123+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:35:09.124+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:35:09.133+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:35:09.138+0000] {standard_task_runner.py:57} INFO - Started process 2210 to run task
[2023-12-04T10:35:09.140+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpj4n9ftzm']
[2023-12-04T10:35:09.141+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask copying_file
[2023-12-04T10:35:09.181+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:35:09.236+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:35:09.237+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:35:09.238+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T10:35:09.248+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:35:09.251+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T10:35:09.251+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:35:09.259+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:35:09.262+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T103509, end_date=20231204T103509
[2023-12-04T10:35:09.272+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 66 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2210)
[2023-12-04T10:35:09.312+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:35:09.333+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:39:24.701+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:39:24.708+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:39:24.708+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:39:24.717+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:39:24.721+0000] {standard_task_runner.py:57} INFO - Started process 2298 to run task
[2023-12-04T10:39:24.724+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmppempwsdy']
[2023-12-04T10:39:24.724+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask copying_file
[2023-12-04T10:39:24.758+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:39:24.808+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:39:24.809+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:39:24.810+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T10:39:24.819+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:39:24.821+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T10:39:24.822+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:39:24.829+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:39:24.832+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T103924, end_date=20231204T103924
[2023-12-04T10:39:24.841+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2298)
[2023-12-04T10:39:24.856+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:39:24.875+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:41:25.883+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:41:25.889+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:41:25.890+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:41:25.901+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:41:25.905+0000] {standard_task_runner.py:57} INFO - Started process 2354 to run task
[2023-12-04T10:41:25.907+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpn0r7ip4x']
[2023-12-04T10:41:25.908+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask copying_file
[2023-12-04T10:41:25.944+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:41:26.001+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:41:26.003+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:41:26.004+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/ >> /dev/null 2>&1']
[2023-12-04T10:41:26.014+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:41:26.018+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:41:26.027+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:41:26.031+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T104125, end_date=20231204T104126
[2023-12-04T10:41:26.044+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2354)
[2023-12-04T10:41:26.079+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:41:26.100+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:50:34.555+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:50:34.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:50:34.562+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:50:34.574+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:50:34.579+0000] {standard_task_runner.py:57} INFO - Started process 2523 to run task
[2023-12-04T10:50:34.582+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8rep0jrc']
[2023-12-04T10:50:34.583+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask copying_file
[2023-12-04T10:50:34.619+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:50:34.679+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:50:34.680+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:50:34.681+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/ >> /dev/null 2>&1']
[2023-12-04T10:50:34.691+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:50:34.693+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:50:34.704+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:50:34.709+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T105034, end_date=20231204T105034
[2023-12-04T10:50:34.720+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 78 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2523)
[2023-12-04T10:50:34.754+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:50:34.775+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:53:22.559+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:53:22.566+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T10:53:22.567+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:53:22.577+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T10:53:22.583+0000] {standard_task_runner.py:57} INFO - Started process 2587 to run task
[2023-12-04T10:53:22.585+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpbcc7beev']
[2023-12-04T10:53:22.586+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask copying_file
[2023-12-04T10:53:22.623+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:53:22.682+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T10:53:22.684+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:53:22.685+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T10:53:22.695+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:53:22.698+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T10:53:22.698+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:53:22.706+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:53:22.708+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T105322, end_date=20231204T105322
[2023-12-04T10:53:22.717+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2587)
[2023-12-04T10:53:22.757+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:53:22.777+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T11:02:36.755+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:02:36.762+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:02:36.762+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T11:02:36.771+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T11:02:36.776+0000] {standard_task_runner.py:57} INFO - Started process 2755 to run task
[2023-12-04T11:02:36.778+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp1ao_gi9v']
[2023-12-04T11:02:36.779+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask copying_file
[2023-12-04T11:02:36.814+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T11:02:36.872+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T11:02:36.874+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T11:02:36.875+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T11:02:36.884+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T11:02:36.886+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T11:02:36.887+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T11:02:36.895+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T11:02:36.897+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T110236, end_date=20231204T110236
[2023-12-04T11:02:36.907+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2755)
[2023-12-04T11:02:36.950+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T11:02:36.973+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T11:05:27.335+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:05:27.342+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [queued]>
[2023-12-04T11:05:27.342+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T11:05:27.352+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copying_file> on 2023-11-30 21:10:00+00:00
[2023-12-04T11:05:27.356+0000] {standard_task_runner.py:57} INFO - Started process 2819 to run task
[2023-12-04T11:05:27.358+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'copying_file', 'scheduled__2023-11-30T21:10:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplgod93tm']
[2023-12-04T11:05:27.359+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask copying_file
[2023-12-04T11:05:27.396+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.copying_file scheduled__2023-11-30T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T11:05:27.447+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='copying_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-30T21:10:00+00:00'
[2023-12-04T11:05:27.448+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T11:05:27.449+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp kaggle.json ~/.kaggle/']
[2023-12-04T11:05:27.459+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T11:05:27.462+0000] {subprocess.py:93} INFO - cp: cannot stat 'kaggle.json': No such file or directory
[2023-12-04T11:05:27.462+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T11:05:27.471+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T11:05:27.473+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=copying_file, execution_date=20231130T211000, start_date=20231204T110527, end_date=20231204T110527
[2023-12-04T11:05:27.483+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task copying_file (Bash command failed. The command returned a non-zero exit code 1.; 2819)
[2023-12-04T11:05:27.490+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T11:05:27.510+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
