[2023-12-04T09:02:57.636+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates manual__2023-12-04T09:02:55.726037+00:00 [queued]>
[2023-12-04T09:02:57.642+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates manual__2023-12-04T09:02:55.726037+00:00 [queued]>
[2023-12-04T09:02:57.643+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:02:57.653+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-12-04 09:02:55.726037+00:00
[2023-12-04T09:02:57.657+0000] {standard_task_runner.py:57} INFO - Started process 579 to run task
[2023-12-04T09:02:57.660+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'manual__2023-12-04T09:02:55.726037+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpgspjmbo0']
[2023-12-04T09:02:57.661+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask updates
[2023-12-04T09:02:57.704+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates manual__2023-12-04T09:02:55.726037+00:00 [running]> on host ed47267dc344
[2023-12-04T09:02:57.768+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T09:02:55.726037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T09:02:55.726037+00:00'
[2023-12-04T09:02:57.769+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:02:57.770+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo apt update']
[2023-12-04T09:02:57.780+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:02:57.814+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:02:57.815+0000] {subprocess.py:93} INFO - We trust you have received the usual lecture from the local System
[2023-12-04T09:02:57.815+0000] {subprocess.py:93} INFO - Administrator. It usually boils down to these three things:
[2023-12-04T09:02:57.815+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:02:57.816+0000] {subprocess.py:93} INFO -     #1) Respect the privacy of others.
[2023-12-04T09:02:57.816+0000] {subprocess.py:93} INFO -     #2) Think before you type.
[2023-12-04T09:02:57.816+0000] {subprocess.py:93} INFO -     #3) With great power comes great responsibility.
[2023-12-04T09:02:57.816+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:02:57.816+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2023-12-04T09:02:57.817+0000] {subprocess.py:93} INFO - sudo: a password is required
[2023-12-04T09:02:57.817+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T09:02:57.825+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T09:02:57.828+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=updates, execution_date=20231204T090255, start_date=20231204T090257, end_date=20231204T090257
[2023-12-04T09:02:57.838+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task updates (Bash command failed. The command returned a non-zero exit code 1.; 579)
[2023-12-04T09:02:57.872+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T09:02:57.892+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
