[2023-12-04T10:21:39.724+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.setting_kaggle manual__2023-12-04T10:21:28.714766+00:00 [queued]>
[2023-12-04T10:21:39.730+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.setting_kaggle manual__2023-12-04T10:21:28.714766+00:00 [queued]>
[2023-12-04T10:21:39.731+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:21:39.740+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): setting_kaggle> on 2023-12-04 10:21:28.714766+00:00
[2023-12-04T10:21:39.745+0000] {standard_task_runner.py:57} INFO - Started process 1860 to run task
[2023-12-04T10:21:39.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'setting_kaggle', 'manual__2023-12-04T10:21:28.714766+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpiebsemb4']
[2023-12-04T10:21:39.747+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask setting_kaggle
[2023-12-04T10:21:39.777+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.setting_kaggle manual__2023-12-04T10:21:28.714766+00:00 [running]> on host ed47267dc344
[2023-12-04T10:21:39.830+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='setting_kaggle' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T10:21:28.714766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T10:21:28.714766+00:00'
[2023-12-04T10:21:39.831+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:21:39.832+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir -p ~/.kaggle /n cp kaggle.json ~/.kaggle/ /n chmod 600 ~/.kaggle/kaggle.json']
[2023-12-04T10:21:39.839+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:21:39.845+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/n’: Permission denied
[2023-12-04T10:21:39.846+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/n’: Permission denied
[2023-12-04T10:21:39.846+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T10:21:39.854+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T10:21:39.856+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=Georgy, task_id=setting_kaggle, execution_date=20231204T102128, start_date=20231204T102139, end_date=20231204T102139
[2023-12-04T10:21:39.865+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task setting_kaggle (Bash command failed. The command returned a non-zero exit code 1.; 1860)
[2023-12-04T10:21:39.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T10:21:39.897+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
